# Generated by Django 4.2.23 on 2025-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='key',
            field=models.BinaryField(default=bytes),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='nonce',
            field=models.BinaryField(default=bytes),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='tag',
            field=models.BinaryField(default=bytes),
        ),
    ]
