# Generated by Django 4.2.23 on 2025-06-23 08:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_encryptedfile_key_encryptedfile_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_expiry),
        ),
    ]
