# Generated by Django 4.2.23 on 2025-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_encryptedfile_has_been_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
